### ISSUE TITLE
FastShadowView Bug

### ISSUE THREAD

**Issue by H-Killer** [alan-eu/react-native-fast-shadow#2]
**React Native version: latest**
**Expo: latest**
**Device - OS: A30 Samsung - Android 11**
### Error:
`requireNativeComponent: "FastShadowView" was not found in the UIManager.`

![code](https://user-images.githubusercontent.com/77407860/198861315-b5e5bf93-6e3f-4915-b377-5c565bd8c2a5.png)

**Comment by simontreny** [comment]
Thanks for reporting this issue @H-Killer.

This error is expected when `react-native-fast-shadow` is used with Expo Go as the library uses native code on Android that is not included in the Expo Go app. In order to fix this, you will need to make a custom Expo build for your app and use it in place of Expo Go. Note that you won't need this on iOS as the iOS implementation doesn't use native code (`ShadowedView` is just an alias of `View`).

You can find the instructions on how to create a custom Expo build [here](https://docs.expo.dev/development/getting-started/).

**Comment by H-Killer** [comment]
> Thanks for reporting this issue @H-Killer.
> 
> This error is expected when `react-native-fast-shadow` is used with Expo Go as the library uses native code on Android that is not included in the Expo Go app. In order to fix this, you will need to make a custom Expo build for your app and use it in place of Expo Go. Note that you won't need this on iOS as the iOS implementation doesn't use native code (`ShadowedView` is just an alias of `View`).
> 
> You can find the instructions on how to create a custom Expo build [here](https://docs.expo.dev/development/getting-started/).

Thanks a lot for answering me.
